default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: postgres
  host: localhost

development:
  <<: *default
  database: predict-backend_development

test:
  <<: *default
  database: predict-backend_test

production:
  <<: *default
  database: predict-backend_production

